version: '3.7'

services:
  nginx:
    image: jboesl/docker-nginx-headers-more:latest
    container_name: nginx-reverse-proxy

    volumes:
      - ./configs/nginx/nginx.conf:/etc/nginx/nginx.conf
    network_mode: host